#!/usr/bin/env python3
"""Independent receipt checker for the MULTI-MATCHING CENSUS stage (the
owner's post-projection refinement, 2026-11-05 session 2): does the
genuinely-matched multi-matching SURVIVE PROJECTION ONTO THE GRAPH?

The census question, as ruled: for every record with 2+ occurrences
(the verified occurrence set of the read-matched stage receipts), project
ALL its occurrences onto graph nodes and bin its mass by what SURVIVES:
  (f) SAME GRAPH NODE after projection (the graph already condenses the
      copies — benign, counted separately and prominently);
  (g) DISTINCT nodes but ALIGNED-TOGETHER — the syng's own homologous-
      interval machinery (query_region_with_anchors, any strand: the node
      projection is orientation-free) ties the two windows' material;
      the condensation-level artifact class (near-identical copies the
      graph kept as parallel segments instead of shared blocks);
  (h) distinct nodes, same window, NOT aligned together (genuinely
      distinct local material), with the same-PATH same-window pairs
      reported as their own sub-class (the syng's self-homology cannot
      discriminate them);
  (i) same chromosome, other windows (adjacent reported separately);
  (j) different chromosome/contig.

Per tail locus (chrI 7/8/13/15/16/18, chrMT 2/6/10) and per truth-rank1
control (chrMT 3/5, chrI 4/5/6/12): the mass table per bin, the
TRUTH-LEAK accounting (mass generated by truth routes projecting onto
nodes/edges OUTSIDE the truth pair's usage, binned the same way — the
share-split-penalizes-truth test), the winner's harvested extra mass
decomposed by the same bins, and the near-twin condensation answer for
the named routes (chrMT 5599/5616, chrI 5397/5545: shared vs parallel
nodes, where the distinguishing material sits).

Per-locus bin semantics (share units; every covered key of every
contributing record lands in exactly one bin):
  COLLECTED — the key is inside the truth pair's usage (the truth
              candidate collects the record's share there, homing or
              not);
  FRAME     — covered by exactly one occurrence, on a truth path: the
              truth route's own material the candidate did not spell
              (clip/cross-window row structure — the partition-spine
              frame class, kept separate from the multi-matching
              question);
  (f)       — covered by 2+ occurrences: the SAME graph node survives
              at multiple panel locations (split by whether a truth-
              path occurrence is among the coverers);
  (g)/(h)   — covered by exactly one off-truth occurrence that shares a
              window with one of the record's truth occurrences
              (homing records) or sits in the locus's own window
              (non-homing records), split by the syng's alignment
              verdict between the covering path and the truth path;
  (i)/(j)   — no shared window: same component chromosome vs other
              contig.

Validates, from the receipts on disk and nothing else:
  phase 1 — the census run markers (exit 0, walls, the 64GiB external RSS
            guard), the in-log read-matched occurrence census, and the
            alignment-cache receipts (markers, walls, and the FULL
            request re-derivation: every re-derived request line matches
            the committed requests receipt, every request has a
            completion marker with matching extents, and per-request hit
            counts match the emitted intervals);
  phase 2 — receipt identity: the multicensus likelihood receipt is
            semantically identical to the committed read-matched receipt
            (only the documented HashMap-order observed-norm ULPs), and
            every sidecar + the admission diagnostic are byte-identical
            (the census emission perturbs nothing);
  phase 3 — census consistency: record counts, the occurrence census
            with the forward-empty/rc-only decomposition, truth-route
            resolution (diagnostic source ids == panel path ids, checked
            against the panel names), and the END-TO-END KEY VALIDATION —
            per locus, per contributing record, the census-derived
            universe-restricted covered node/edge sets reproduce the
            committed ingredients' sets exactly, plus per-record share
            equality (folded into the streaming master pass);
  phase 4 — THE POST-PROJECTION PAIR CENSUS: the full pair re-derivation
            (every pair of every record's occurrences, both components)
            reproduces every record's committed physical pair_bins, and
            the post-projection bin table (f/g/h/hsp/i/j with the
            same-path and physical cross-tabs);
  phase 5 — the per-locus mass tables at every locus: the truth-homing
            decomposition (collected / frame / f / g / h / i / j) and the
            non-homing decomposition, both with exact mass conservation,
            the winner's extra mass decomposed per bin, and the
            share-split dilution;
  phase 6 — the near-twin condensation: the named route pairs' shared vs
            parallel node structure from the walk and homology receipts,
            their census pair structure, and where the distinguishing
            material sits;
  phase 7 — the verdict table: tail loci vs controls, pooled.

Assessment-side only. No product file is read or written. No threshold
enters any instrument; the census is a pure measurement. The alignment
padding (120) is the syng probe's own existing choice, passed per
request. The window-extent rule is stated in AlignmentCache.extent: the
territory axis range on the component's own contigs, the census
matched-material hull ([start, start + 150 + 50) — the matched spans
lie inside [start, start + READ_LENGTH)) elsewhere.
"""

import json
import os
import re
import sys
import collections

DATA = "/home/erikg/yeast/genome-balanced-diploid-validation-20260930"
PANEL = "/home/erikg/yeast/syng-k63-s8-seed7-acgt-only/yeast235.syng.names"
SCRATCH = f"{DATA}/cosine-diagnostic-scratch"
GUARD_KIB = 64 * 1024 * 1024
K = 63                       # the panel's syncmer window length
READ_LENGTH = 150
EXTENT_SLACK = 50            # the matched-material hull's right margin
ALIGNMENT_PADDING = 120      # the syng probe's own existing choice
COMPONENTS = ("chrMT", "chrI")
TAIL_LOCI = {"chrI": [7, 8, 13, 15, 16, 18], "chrMT": [2, 6, 10]}
CONTROL_LOCI = {"chrMT": [3, 5], "chrI": [4, 5, 6, 12]}
NEAR_TWINS = {"chrMT": (5599, 5616), "chrI": (5397, 5545)}

# The committed emission's physical pair bins (validated by re-derivation).
PHYSICAL = ["same_window", "adjacent_window", "same_contig_far", "other_contig"]
COMMITTED_PAIR_BINS = [f"coalesced_{name}" for name in PHYSICAL] + PHYSICAL

# The post-projection bins.
F = "f_same_node"
G = "g_aligned_together"
H = "h_same_window_not_aligned"
HSP = "h_same_path_same_window"
I_ADJ = "i_adjacent_window"
I_FAR = "i_same_chromosome_other_window"
J = "j_different_chromosome"
POST_BINS = [F, G, H, HSP, I_ADJ, I_FAR, J]

FAILURES = []


def fail(message):
    FAILURES.append(message)
    print(f"FAIL: {message}")


def check(condition, message):
    if condition:
        print(f"ok: {message}")
    else:
        fail(message)


def load_census(path):
    out = {}
    with open(path) as handle:
        for line in handle:
            row = json.loads(line)
            out[row["locus"]] = row
    return out


def load_diagnostic(path):
    header = None
    loci = {}
    with open(path) as handle:
        for line in handle:
            row = json.loads(line)
            if row.get("kind") == "admission-diagnostic-header":
                header = row
            else:
                loci[row["locus"]] = row
    return header, loci


def load_ingredients(path):
    out = {}
    with open(path) as handle:
        for line in handle:
            row = json.loads(line)
            out[row["locus"]] = row
    return out


def parse_census(err_path):
    with open(err_path) as handle:
        text = handle.read()
    match = re.search(
        r"\[read-matched\] records (\d+) occurrences (\d+) "
        r"gapped-occurrences (\d+) span-bp (\d+) matched-bp (\d+)",
        text,
    )
    if not match:
        return None
    values = tuple(int(value) for value in match.groups())
    return {
        "records": values[0],
        "occurrences": values[1],
        "gapped": values[2],
        "span_bp": values[3],
        "matched_bp": values[4],
    }


def semantic_diffs(old, new):
    """Field-level comparison ignoring the documented HashMap-order
    observed-norm ULPs; returns (other-diffs, norm-ulp-diffs)."""
    other = []
    ulp = []
    for locus, row in new.items():
        assert locus in old
        for key, value in row.items():
            if key in ("observed_node_norm", "observed_edge_norm"):
                if old[locus].get(key) != value:
                    ulp.append((locus, key, old[locus].get(key), value))
            elif old[locus].get(key) != value:
                other.append((locus, key))
    return other, ulp


def load_names():
    """Panel path id -> (full name, contig)."""
    names = {}
    with open(PANEL) as handle:
        for line in handle:
            fields = line.split()
            names[int(fields[0])] = (fields[1], fields[1].rsplit("#", 1)[-1])
    return names


def contig_class(contig, component):
    """The physical location class of a panel path's contig."""
    if contig == component:
        return "component"
    if contig.startswith("block"):
        return "scaffold"
    return "other_chromosome"


class CensusRecord:
    """One routed record's census row, with its occurrence structure
    projected onto graph nodes (the covered shared-segment node ids,
    per matched interval, in path order)."""

    __slots__ = (
        "index", "share", "multiplicity", "t_r", "total",
        "pair_bins", "occ_path", "occ_start", "occ_parts", "occ_contig",
        "occ_contig_class", "occ_truth", "occ_nodes", "occ_edges",
        "key_nodes", "key_edges",
    )

    def __init__(self, row, names, truth_path_set, component):
        self.index = row["record"]
        self.share = row["share"]
        self.multiplicity = row["multiplicity"]
        self.t_r = row["t_r"]
        self.total = row["total_occurrences"]
        self.pair_bins = row["pair_bins"]
        self.occ_path = []
        self.occ_start = []
        self.occ_parts = []
        self.occ_contig = []
        self.occ_contig_class = []
        self.occ_truth = []
        self.occ_nodes = []
        self.occ_edges = []
        self.key_nodes = {}
        self.key_edges = {}
        for occ in row["occurrences"]:
            path = occ["path"]
            nodes = set()
            edges = set()
            for interval in occ["intervals"]:
                previous = None
                for node in interval:
                    nodes.add(node)
                    if previous is not None:
                        edges.add(pack_edge(previous, node))
                    previous = node
            self.occ_path.append(path)
            self.occ_start.append(occ["start"])
            self.occ_parts.append(tuple(occ["partitions"]))
            self.occ_contig.append(names[path][1])
            self.occ_contig_class.append(contig_class(names[path][1], component))
            self.occ_truth.append(path in truth_path_set)
            self.occ_nodes.append(nodes)
            self.occ_edges.append(edges)
            position = len(self.occ_nodes) - 1
            for node in nodes:
                self.key_nodes.setdefault(node, []).append(position)
            for edge in edges:
                self.key_edges.setdefault(edge, []).append(position)

    def homing_at(self, locus):
        """Truth-path occurrences touching the locus's window."""
        return [
            position
            for position in range(len(self.occ_path))
            if self.occ_truth[position] and locus in self.occ_parts[position]
        ]

    def homing_any(self):
        return any(self.occ_truth)


def pack_edge(left, right):
    return (left << 32) | right


def pair_bin_python(record, left, right, component_contig):
    """Independent Python re-derivation of multi_census_pair_bin (the
    committed physical classifier)."""
    nodes_a = record.occ_nodes[left]
    nodes_b = record.occ_nodes[right]
    parts_a = record.occ_parts[left]
    parts_b = record.occ_parts[right]
    coalesced = not nodes_a.isdisjoint(nodes_b)
    if not set(parts_a).isdisjoint(parts_b):
        physical = 0
    elif any(abs(p - q) == 1 for p in parts_a for q in parts_b):
        physical = 1
    elif (
        record.occ_contig[left] == component_contig
        and record.occ_contig[right] == component_contig
    ):
        physical = 2
    else:
        physical = 3
    return physical if coalesced else physical + 4


class AlignmentCache:
    """The syng's own alignment provenance, as dumped by the
    `syng_homology_dump` receipt runs: per (query path, window) the
    homologous intervals the syng reported for each requested target.

    aligned(A, B, w) := the syng, queried from path A's window-w extent,
    reports at least one homologous interval on path B (ANY strand — the
    node projection is orientation-free, so an inverted homolog is still
    aligned-together) overlapping B's window-w extent. B's window-w
    extent is the territory axis range when B sits on the component's
    own contig, else the hull of B's census-matched material in window w
    (the matched spans are inside [start, start + READ_LENGTH))."""

    def __init__(self, path, axis, hulls, names, component):
        self.axis = axis
        self.hulls = hulls
        self.names = names
        self.component = component
        self.intervals = collections.defaultdict(list)
        self.markers = {}
        self.emitted = collections.Counter()  # (query, window) -> interval lines
        with open(path) as handle:
            for line in handle:
                row = json.loads(line)
                if row.get("request_done"):
                    self.markers[(row["query_path"], row["window"])] = (
                        row["qs"], row["qe"], row["hits"],
                    )
                else:
                    self.intervals[(row["query_path"], row["window"], row["target_path"])].append(
                        (row["start"], row["end"])
                    )
                    self.emitted[(row["query_path"], row["window"])] += 1
        self.aligned_memo = {}

    def extent(self, path, window):
        if self.names[path][1] == self.component:
            return self.axis[window][0], self.axis[window][1]
        lo, hi = self.hulls[(path, window)]
        return lo, hi

    def aligned(self, query_path, target_path, window):
        key = (query_path, target_path, window)
        if key in self.aligned_memo:
            return self.aligned_memo[key]
        lo, hi = self.extent(target_path, window)
        result = any(
            start < hi and lo < end
            for (start, end) in self.intervals.get((query_path, window, target_path), ())
        )
        self.aligned_memo[key] = result
        return result

    def aligned_pair(self, left_path, right_path, window):
        """Symmetric: either direction's syng homology ties the window."""
        return self.aligned(left_path, right_path, window) or self.aligned(
            right_path, left_path, window
        )


def load_axis(header):
    """The component's territory windows in spine coordinate order; the
    census partition ids are the component-local window indices."""
    axis = sorted(header["axis"], key=lambda entry: entry["start"])
    return [(entry["start"], entry["end"], entry["group"]) for entry in axis]


def truth_paths(header, names, component):
    """The truth routes' panel path ids (copy 0 = S288C, copy 1 = SK1),
    resolved from the diagnostic header's source ids and validated as
    panel path ids of the component's own contig."""
    out = []
    for route in header["truth_routes"]:
        source = route["segments"][0]["source"]
        name, contig = names[source]
        check(
            contig == component,
            f"truth source {source} is a {component} panel path ({name})",
        )
        out.append(source)
    return out


def _post_bin(record, covering, locus, component, cache, truth, homing):
    """The post-projection bin of one off-truth key's covering structure:
      (f)  2+ covering occurrences (the same node at multiple locations);
      (g)/(h) for homing records: the covering occurrence shares a window
              with one of the record's truth occurrences — aligned
              together per the syng or not;
           for non-homing records: the covering occurrence sits in the
              locus's own window — aligned with a truth path over that
              window per the syng or not;
      (i)/(j) no shared window: same component chromosome vs other
              contig (adjacent pairs arise only in the pair table; here
              every other-window relation is (i))."""
    if len(covering) >= 2:
        return F
    best = None
    for position in covering:
        if record.occ_truth[position]:
            continue
        parts = set(record.occ_parts[position])
        if homing:
            truth_positions = [
                other
                for other in range(len(record.occ_path))
                if record.occ_truth[other]
            ]
            shared_windows = set()
            for other in truth_positions:
                shared_windows |= parts & set(record.occ_parts[other])
            if shared_windows:
                candidate = (
                    G
                    if any(
                        cache.aligned_pair(
                            record.occ_path[position],
                            record.occ_path[other],
                            window,
                        )
                        for other in truth_positions
                        for window in parts & set(record.occ_parts[other])
                    )
                    else H
                )
            elif record.occ_contig[position] == component:
                candidate = I_FAR
            else:
                candidate = J
        else:
            if locus in parts:
                candidate = (
                    G
                    if any(
                        cache.aligned(record.occ_path[position], path, locus)
                        for path in truth
                    )
                    else H
                )
            elif record.occ_contig[position] == component:
                candidate = I_FAR
            else:
                candidate = J
        if best is None or POST_BINS.index(candidate) < POST_BINS.index(best):
            best = candidate
    return best if best is not None else H


HOMING_TARGET = {
    F: "f_homing", G: "g_homing", H: "h_homing", HSP: "h_homing",
    I_ADJ: "i_homing", I_FAR: "i_homing", J: "j_homing",
}
NONHOMING_TARGET = {
    F: "f_nonhoming", G: "g_nonhoming", H: "h_nonhoming", HSP: "h_nonhoming",
    I_ADJ: "i_nonhoming", I_FAR: "i_nonhoming", J: "j_nonhoming",
}


def _account_key(
    table, record, covering, share, key, truth_set, winner_set,
    locus, component, cache, truth, homing, truth_walk,
):
    """Account one (record, key) share unit into the per-locus table (see
    the module docstring's bin semantics). Every key lands in exactly one
    bin; the homing and non-homing decompositions each conserve their
    record classes' mass exactly."""
    in_truth = key in truth_set
    in_winner = key in winner_set
    if in_winner:
        table["winner_total"] += share
        if in_truth:
            table["winner_shared"] += share
    if in_truth:
        if homing:
            table["collected_homing"] += share
        else:
            table["collected_nonhoming"] += share
        return
    # Off the truth pair's usage.
    truth_covered = any(record.occ_truth[position] for position in covering)
    on_truth_sequence = key in truth_walk
    if in_winner:
        if len(covering) == 1 and truth_covered:
            table["winner_extra_frame"] += share
        else:
            post = _post_bin(record, covering, locus, component, cache, truth, homing)
            table["winner_extra"][post] += share
            if on_truth_sequence:
                table["on_truth_sequence"][post] += share
            else:
                table["off_truth_sequence"][post] += share
    if len(covering) >= 2:
        if homing:
            table["f_homing"] += share
            if truth_covered:
                table["f_homing_truth_covered"] += share
        else:
            table["f_nonhoming"] += share
        if on_truth_sequence:
            table["on_truth_sequence"][F] += share
        else:
            table["off_truth_sequence"][F] += share
        return
    if len(covering) == 1 and truth_covered:
        # A truth route's own material, unspelled by the truth candidate.
        if homing:
            table["frame_homing"] += share
        else:
            table["frame_nonhoming"] += share
        return
    post = _post_bin(record, covering, locus, component, cache, truth, homing)
    if homing:
        table[HOMING_TARGET[post]] += share
    else:
        table[NONHOMING_TARGET[post]] += share
    if on_truth_sequence:
        table["on_truth_sequence"][post] += share
    else:
        table["off_truth_sequence"][post] += share


def _new_locus_table():
    return {
        "records_total": 0,
        "records_homing": 0,
        "homing_mass": 0.0,
        "homing_t_mass": 0.0,
        "collected_homing": 0.0,
        "collected_nonhoming": 0.0,
        "frame_homing": 0.0,
        "frame_nonhoming": 0.0,
        "f_homing": 0.0,
        "f_homing_truth_covered": 0.0,
        "g_homing": 0.0,
        "h_homing": 0.0,
        "i_homing": 0.0,
        "j_homing": 0.0,
        "nonhoming_mass": 0.0,
        "f_nonhoming": 0.0,
        "g_nonhoming": 0.0,
        "h_nonhoming": 0.0,
        "i_nonhoming": 0.0,
        "j_nonhoming": 0.0,
        "winner_extra": collections.Counter(),
        "winner_extra_frame": 0.0,
        "winner_total": 0.0,
        "winner_shared": 0.0,
        "homing_split_dest": collections.Counter(),
        # The truth-SEQUENCE membership of off-usage keys (per bin): does
        # the material sit on the truth haplotypes' own panel sequences
        # (the candidate failed to spell material the truth carries) or
        # is it absent from them (foreign material the winner harvests)?
        "on_truth_sequence": collections.Counter(),
        "off_truth_sequence": collections.Counter(),
    }


def main():
    names = load_names()
    print("== phase 1: run markers")
    for component in COMPONENTS:
        prefix = f"run-cosine-multicensus-pilot-{component}"
        exit_path = f"{DATA}/{prefix}.exit"
        check(os.path.exists(exit_path), f"{prefix}.exit exists")
        with open(exit_path) as handle:
            check(handle.read().strip() == "0", f"{prefix} exit 0")
        for sidecar in ("done", "wall", "rss", "stages"):
            check(os.path.exists(f"{DATA}/{prefix}.{sidecar}"), f"{prefix}.{sidecar}")
        with open(f"{DATA}/{prefix}.wall") as handle:
            wall = int(handle.read().strip())
        peak = 0
        with open(f"{DATA}/{prefix}.rss") as handle:
            for line in handle:
                fields = line.split()
                if len(fields) >= 3:
                    peak = max(peak, int(fields[2]))
        check(peak < GUARD_KIB, f"{prefix} external RSS peak {peak} kB under the 64GiB guard")
        census = parse_census(f"{DATA}/{prefix}.err")
        check(census is not None, f"{prefix} run log carries the read-matched occurrence census")
        if census:
            check(census["gapped"] == 0, f"{component} census gapped occurrences 0")
            check(
                census["span_bp"] == census["matched_bp"],
                f"{component} census span-bp == matched-bp",
            )
            print(
                f"   {component}: wall {wall}s, rss peak {peak} kB, "
                f"records {census['records']}, observed-pass occurrences {census['occurrences']}"
            )
        for suffix in ("done", "exit", "wall"):
            check(
                os.path.exists(f"{SCRATCH}/{component}/multi-census-alignment.{suffix}"),
                f"{component} alignment cache .{suffix} marker",
            )
        exit_file = f"{SCRATCH}/{component}/multi-census-alignment.exit"
        if os.path.exists(exit_file):
            with open(exit_file) as handle:
                check(handle.read().strip() == "0", f"{component} alignment cache exit 0")
            with open(f"{SCRATCH}/{component}/multi-census-alignment.wall") as handle:
                print(f"   {component}: alignment cache wall {handle.read().strip()}s")
        check(
            os.path.exists(f"{SCRATCH}/{component}/multi-census-alignment-requests.tsv"),
            f"{component} alignment requests receipt exists",
        )

    print("\n== phase 2: receipt identity (the census emission perturbs nothing)")
    for component in COMPONENTS:
        before = load_census(f"{DATA}/cosine-graph-likelihood-readmatched-{component}.jsonl")
        after = load_census(f"{SCRATCH}/{component}/cosine-graph-likelihood-multicensus.jsonl")
        other, ulp = semantic_diffs(before, after)
        check(not other, f"{component} multicensus receipt semantically identical ({other})")
        if ulp:
            worst = max(
                abs(old_value - new_value) / max(abs(old_value), 1e-300)
                for _, _, old_value, new_value in ulp
            )
            print(
                f"   {component}: {len(ulp)} observed-norm ULP fields only, "
                f"max relative {worst:.2e}"
            )
        for sidecar in ("ties", "competitors", "records", "ingredients"):
            with open(f"{SCRATCH}/{component}/cosine-graph-likelihood-multicensus.jsonl.{sidecar}.jsonl", "rb") as a:
                with open(f"{DATA}/cosine-graph-likelihood-readmatched-{component}.jsonl.{sidecar}.jsonl", "rb") as b:
                    check(
                        a.read() == b.read(),
                        f"{component} {sidecar} sidecar byte-identical with the committed receipt",
                    )
        with open(f"{SCRATCH}/{component}/cosine-admission-diagnostic-multicensus.jsonl", "rb") as a:
            with open(f"{DATA}/cosine-admission-diagnostic-readmatched-{component}.jsonl", "rb") as b:
                check(a.read() == b.read(), f"{component} admission diagnostic byte-identical")

    print("\n== phase 3: census consistency (streaming pre-pass)")
    receipts = {
        component: load_census(f"{DATA}/cosine-graph-likelihood-readmatched-{component}.jsonl")
        for component in COMPONENTS
    }
    ingredients = {
        component: load_ingredients(
            f"{DATA}/cosine-graph-likelihood-readmatched-{component}.jsonl.ingredients.jsonl"
        )
        for component in COMPONENTS
    }
    state = {}
    for component in COMPONENTS:
        header, _ = load_diagnostic(
            f"{DATA}/cosine-admission-diagnostic-readmatched-{component}.jsonl"
        )
        axis = load_axis(header)
        truth = truth_paths(header, names, component)
        err_census = parse_census(f"{DATA}/run-cosine-multicensus-pilot-{component}.err")
        # The pre-pass: matched-material hulls per (path, window), window
        # participants, and the record/occurrence counts.
        hulls = {}
        participants = collections.defaultdict(set)
        record_count = 0
        occurrence_count = 0
        observed_pass_occ = 0
        with open(f"{SCRATCH}/{component}/cosine-multi-census.jsonl") as handle:
            for line in handle:
                row = json.loads(line)
                record_count += 1
                if any(occ["orientation"] == 0 for occ in row["occurrences"]):
                    observed_pass_occ += len(row["occurrences"])
                for occ in row["occurrences"]:
                    path = occ["path"]
                    for window in occ["partitions"]:
                        key = (path, window)
                        lo, hi = hulls.get(
                            key, (occ["start"], occ["start"] + READ_LENGTH + EXTENT_SLACK)
                        )
                        hulls[key] = (
                            min(lo, occ["start"]),
                            max(hi, occ["start"] + READ_LENGTH + EXTENT_SLACK),
                        )
                        participants[window].add(path)
                    occurrence_count += 1
        check(
            record_count == err_census["records"],
            f"{component} census record count == the run's routed slice ({record_count})",
        )
        check(
            observed_pass_occ == err_census["occurrences"],
            f"{component} forward-present records' occurrences == the observed-pass census "
            f"({observed_pass_occ})",
        )
        check(
            occurrence_count >= observed_pass_occ,
            f"{component} census occurrences {occurrence_count} include the observed pass",
        )
        print(
            f"   {component}: {record_count} records, {occurrence_count} census occurrences "
            f"({observed_pass_occ} enumerated by the observed pass + "
            f"{occurrence_count - observed_pass_occ} rc-only); "
            f"{len(hulls)} (path, window) extents, truth paths {truth}"
        )
        state[component] = (axis, truth, hulls, participants)

    print("\n== phase 4+5: the post-projection census (streaming master pass)")
    pair_tables = {}
    locus_tables = {}
    twin_census = {}
    key_validation = {"checked": 0, "bad_keys": 0, "bad_shares": 0, "bad_pairs": 0}
    for component in COMPONENTS:
        axis, truth, hulls, participants = state[component]
        truth_path_set = set(truth)
        cache = AlignmentCache(
            f"{SCRATCH}/{component}/multi-census-alignment.jsonl",
            axis,
            hulls,
            names,
            component,
        )
        # The per-locus accounting targets, from the committed receipts and
        # ingredients: universe/truth/winner key sets and the per-record
        # entries (inverted for the streaming pass).
        locus_keys = {}
        record_loci = collections.defaultdict(list)
        for locus, ingredient in sorted(ingredients[component].items()):
            universe_nodes = set()
            universe_edges = set()
            for row in ingredient["rows"]:
                for entry in row["nodes"]:
                    universe_nodes.add(entry[0])
                for entry in row["edges"]:
                    universe_edges.add(entry[0])
            receipt = receipts[component][locus]
            truth_rows = receipt.get("truth_graph_rows") or []
            truth_nodes = set()
            truth_edges = set()
            for index in truth_rows:
                row = ingredient["rows"][index]
                for entry in row["nodes"]:
                    truth_nodes.add(entry[0])
                for entry in row["edges"]:
                    truth_edges.add(entry[0])
            called = receipt.get("qual_called_classes") or []
            winner_rows = called[0]["row_indices"] if called else []
            winner_nodes = set()
            winner_edges = set()
            for index in winner_rows:
                row = ingredient["rows"][index]
                for entry in row["nodes"]:
                    winner_nodes.add(entry[0])
                for entry in row["edges"]:
                    winner_edges.add(entry[0])
            locus_keys[locus] = (
                universe_nodes, universe_edges,
                truth_nodes, truth_edges,
                winner_nodes, winner_edges,
            )
            for entry in ingredient["records"]:
                record_loci[entry["record"]].append((locus, entry))

        truth_walk_keys = set()
        for truth_path in truth:
            walk_path = f"{SCRATCH}/{component}/truth-walk-{truth_path}.tsv"
            check(os.path.exists(walk_path), f"{component} truth walk receipt {walk_path}")
            previous = None
            with open(walk_path) as walk_handle:
                for walk_line in walk_handle:
                    bp, node = walk_line.split()
                    node = abs(int(node))
                    truth_walk_keys.add(node)
                    if previous is not None:
                        truth_walk_keys.add(pack_edge(previous, node))
                    previous = node
        print(
            f"   {component}: truth-sequence walks loaded "
            f"({len(truth)} paths)"
        )
        pair_counts = collections.Counter()
        pair_records = collections.Counter()
        pair_share = collections.Counter()
        pending_partners = collections.defaultdict(set)
        twins = NEAR_TWINS[component]
        twin_pairs = collections.Counter()
        tables = {}
        with open(f"{SCRATCH}/{component}/cosine-multi-census.jsonl") as handle:
            for line in handle:
                row = json.loads(line)
                record = CensusRecord(row, names, truth_path_set, component)
                count = len(record.occ_path)
                bins_here = collections.Counter()
                for left in range(count):
                    for right in range(left + 1, count):
                        committed = pair_bin_python(record, left, right, component)
                        bins_here[COMMITTED_PAIR_BINS[committed]] += 1
                        if {record.occ_path[left], record.occ_path[right]} == set(twins):
                            twin_pairs[COMMITTED_PAIR_BINS[committed]] += 1
                        if committed < 4:
                            post = F
                            if record.occ_path[left] == record.occ_path[right]:
                                pair_counts["f_same_path"] += 1
                            else:
                                pair_counts["f_cross_path"] += 1
                        elif committed == 4:
                            if record.occ_path[left] == record.occ_path[right]:
                                post = HSP
                            else:
                                shared = (
                                    set(record.occ_parts[left])
                                    & set(record.occ_parts[right])
                                )
                                for window in shared:
                                    pending_partners[(record.occ_path[left], window)].add(
                                        record.occ_path[right]
                                    )
                                    pending_partners[(record.occ_path[right], window)].add(
                                        record.occ_path[left]
                                    )
                                post = (
                                    G
                                    if any(
                                        cache.aligned_pair(
                                            record.occ_path[left],
                                            record.occ_path[right],
                                            window,
                                        )
                                        for window in shared
                                    )
                                    else H
                                )
                        elif committed == 5:
                            post = I_ADJ
                        elif committed == 6:
                            post = I_FAR
                        else:
                            post = J
                        pair_counts[post] += 1
                        bins_here[post] += 1
                for name in COMMITTED_PAIR_BINS:
                    if record.pair_bins[name] != bins_here.get(name, 0):
                        key_validation["bad_pairs"] += 1
                        fail(
                            f"{component} record {record.index} committed {name} "
                            f"{record.pair_bins[name]} != re-derived {bins_here.get(name, 0)}"
                        )
                if count >= 2:
                    for name in POST_BINS:
                        if bins_here.get(name, 0):
                            pair_records[name] += 1
                            pair_share[name] += record.share
                # The per-locus accounting for every locus this record
                # contributes to, plus the end-to-end key validation.
                for locus, entry in record_loci.get(record.index, ()):
                    (
                        universe_nodes, universe_edges,
                        truth_nodes, truth_edges,
                        winner_nodes, winner_edges,
                    ) = locus_keys[locus]
                    table = tables.setdefault(locus, _new_locus_table())
                    table["records_total"] += 1
                    share = record.share
                    homing = record.homing_at(locus)
                    key_count = len(entry["nodes"]) + len(entry["edges"])
                    if homing:
                        table["records_homing"] += 1
                        table["homing_mass"] += share * key_count
                        table["homing_t_mass"] += share * record.t_r * key_count
                        other_partitions = set()
                        for position in range(count):
                            other_partitions.update(record.occ_parts[position])
                        for partition in other_partitions:
                            if partition != locus:
                                distance = abs(partition - locus)
                                table["homing_split_dest"][
                                    1 if distance == 1 else (2 if distance <= 3 else 4)
                                ] += share
                    else:
                        table["nonhoming_mass"] += share * key_count
                    key_validation["checked"] += 1
                    if abs(record.share - entry["share"]) > 0:
                        key_validation["bad_shares"] += 1
                    node_set = {node for node in record.key_nodes if node in universe_nodes}
                    edge_set = {edge for edge in record.key_edges if edge in universe_edges}
                    if node_set != set(entry["nodes"]) or edge_set != set(entry["edges"]):
                        key_validation["bad_keys"] += 1
                    for node in entry["nodes"]:
                        _account_key(
                            table, record, record.key_nodes.get(node, []), share,
                            node, truth_nodes, winner_nodes, locus, component,
                            cache, truth, homing, truth_walk_keys,
                        )
                    for edge in entry["edges"]:
                        _account_key(
                            table, record, record.key_edges.get(edge, []), share,
                            edge, truth_edges, winner_edges, locus, component,
                            cache, truth, homing, truth_walk_keys,
                        )
        check(
            key_validation["bad_pairs"] == 0,
            f"{component} full pair re-derivation reproduces every record's committed "
            f"pair_bins (key-validation bad pairs so far: {key_validation['bad_pairs']})",
        )
        # The request re-derivation: rebuild every request line exactly as
        # the receipt run was driven (pending partners, hulls, axis) and
        # compare with the committed requests receipt and the completion
        # markers.
        derived_lines = []
        for (path, window), partners_set in sorted(pending_partners.items()):
            if names[path][1] == component:
                qs, qe = axis[window][0], axis[window][1]
            else:
                lo, hi = hulls[(path, window)]
                qs, qe = lo, hi
            if path in truth_path_set:
                targets = sorted(participants[window] | truth_path_set)
            else:
                targets = sorted(partners_set | truth_path_set)
            derived_lines.append(
                f"{path}\t{window}\t{qs}\t{qe}\t{ALIGNMENT_PADDING}\t"
                + ",".join(map(str, targets))
            )
        with open(f"{SCRATCH}/{component}/multi-census-alignment-requests.tsv") as handle:
            receipt_lines = [line.rstrip("\n") for line in handle if line.strip()]
        check(
            derived_lines == receipt_lines,
            f"{component} re-derived alignment requests == the committed requests receipt "
            f"({len(derived_lines)} lines)",
        )
        missing = [
            (path, window)
            for (path, window) in pending_partners
            if (path, window) not in cache.markers
        ]
        check(
            not missing,
            f"{component} every re-derived request has a completion marker "
            f"(first missing: {missing[:3]})",
        )
        bad_extents = [
            (path, window, cache.markers[(path, window)])
            for (path, window) in pending_partners
            if (path, window) in cache.markers
            and (cache.markers[(path, window)][0], cache.markers[(path, window)][1]) != (
                (axis[window][0], axis[window][1])
                if names[path][1] == component
                else hulls[(path, window)]
            )
        ]
        check(
            not bad_extents,
            f"{component} every completion marker carries the re-derived extent "
            f"(first bad: {bad_extents[:3]})",
        )
        # Per-request hit accounting: markers vs emitted interval lines.
        hit_mismatches = [
            key
            for key, (qs, qe, hits) in cache.markers.items()
            if cache.emitted.get(key, 0) != hits
        ]
        check(
            not hit_mismatches,
            f"{component} per-request marker hit counts match the emitted intervals "
            f"(first bad: {hit_mismatches[:3]})",
        )
        pair_tables[component] = (pair_counts, pair_records, pair_share)
        locus_tables[component] = tables
        twin_census[component] = dict(twin_pairs)

    check(
        key_validation["bad_keys"] == 0,
        f"END-TO-END KEY VALIDATION: census-derived universe-restricted covered keys "
        f"reproduce the committed ingredients ({key_validation['checked']} (record, locus) "
        f"pairs, {key_validation['bad_keys']} bad)",
    )
    check(
        key_validation["bad_shares"] == 0,
        f"census shares == ingredient shares ({key_validation['checked']} checks)",
    )

    print("\n== phase 4 report: the post-projection pair census (all pairs of occurrences)")
    for component in COMPONENTS:
        pair_counts, pair_records, pair_share = pair_tables[component]
        total_pairs = sum(pair_counts[name] for name in POST_BINS)
        print(f"   {component}: {total_pairs:,d} occurrence pairs")
        for name in POST_BINS:
            share_of = 100.0 * pair_counts[name] / total_pairs if total_pairs else 0
            print(
                f"      {name:34s} pairs {pair_counts[name]:>13,d} ({share_of:6.2f}%)  "
                f"records {pair_records[name]:>6,d}  records-with-bin share mass "
                f"{pair_share[name]:>10.1f}"
            )
        print(
            f"      [f split] same-path pairs {pair_counts['f_same_path']:,d} / "
            f"cross-path {pair_counts['f_cross_path']:,d}"
        )

    print("\n== phase 5 report: the per-locus post-projection mass tables (share units)")
    for component in COMPONENTS:
        for locus, receipt in sorted(receipts[component].items()):
            table = locus_tables[component].get(locus)
            if table is None:
                continue
            mass = receipt["observed_node_mass"] + receipt["observed_edge_mass"]
            homing_decomposed = (
                table["collected_homing"]
                + table["frame_homing"]
                + table["f_homing"]
                + table["g_homing"]
                + table["h_homing"]
                + table["i_homing"]
                + table["j_homing"]
            )
            check(
                abs(homing_decomposed - table["homing_mass"])
                <= 1e-6 * max(1.0, table["homing_mass"]),
                f"{component} L{locus} homing mass decomposes exactly "
                f"({table['homing_mass']:.1f} = {homing_decomposed:.1f})",
            )
            nonhoming_decomposed = (
                table["collected_nonhoming"]
                + table["frame_nonhoming"]
                + table["f_nonhoming"]
                + table["g_nonhoming"]
                + table["h_nonhoming"]
                + table["i_nonhoming"]
                + table["j_nonhoming"]
            )
            check(
                abs(nonhoming_decomposed - table["nonhoming_mass"])
                <= 1e-6 * max(1.0, table["nonhoming_mass"]),
                f"{component} L{locus} non-homing mass decomposes exactly "
                f"({table['nonhoming_mass']:.1f} = {nonhoming_decomposed:.1f})",
            )
            conserved = table["homing_mass"] + table["nonhoming_mass"]
            check(
                abs(conserved - mass) <= 1e-6 * max(1.0, mass),
                f"{component} L{locus} census mass conserves the locus mass "
                f"({mass:.1f} = {conserved:.1f})",
            )

    def locus_line(component, locus):
        receipt = receipts[component][locus]
        table = locus_tables[component].get(locus)
        mass = receipt["observed_node_mass"] + receipt["observed_edge_mass"]
        rank = receipt.get("truth_rank")
        parts = [f"{component} L{locus}: rank {rank} | mass {mass:.1f}"]
        if table:
            parts.append(
                f"homing {table['records_homing']}/{table['records_total']} records, "
                f"{table['homing_mass']:.1f}: collected {table['collected_homing']:.1f} | "
                f"frame {table['frame_homing']:.1f} | f {table['f_homing']:.1f} "
                f"(truth-covered {table['f_homing_truth_covered']:.1f}) | "
                f"g {table['g_homing']:.1f} | h {table['h_homing']:.1f} | "
                f"i {table['i_homing']:.1f} | j {table['j_homing']:.1f}"
            )
            parts.append(
                f"non-homing {table['nonhoming_mass']:.1f}: collected "
                f"{table['collected_nonhoming']:.1f} | frame {table['frame_nonhoming']:.1f} | "
                f"f {table['f_nonhoming']:.1f} | g {table['g_nonhoming']:.1f} | "
                f"h {table['h_nonhoming']:.1f} | i {table['i_nonhoming']:.1f} | "
                f"j {table['j_nonhoming']:.1f}"
            )
            winner = table["winner_extra"]
            parts.append(
                f"winner extra {sum(winner.values()):.1f} "
                f"(frame {table['winner_extra_frame']:.1f}): "
                + " ".join(f"{name}={winner[name]:.1f}" for name in POST_BINS if winner[name])
            )
            parts.append(
                f"dilution {table['homing_t_mass'] - table['homing_mass']:.1f} "
                f"(t-weighted {table['homing_t_mass']:.1f})"
            )
        return " | ".join(parts)

    for component in COMPONENTS:
        print(f"\n   {component} per-locus tables:")
        for locus in sorted(receipts[component]):
            print("   " + locus_line(component, locus))

    print("\n== phase 6: the near-twin condensation (the named routes)")
    for component in COMPONENTS:
        left, right = NEAR_TWINS[component]
        for receipt_name in (
            f"near-twin-walk-{left}.tsv",
            f"near-twin-walk-{right}.tsv",
            f"near-twin-homology-{left}-{right}.jsonl",
            f"near-twin-homology-{right}-{left}.jsonl",
        ):
            check(
                os.path.exists(f"{SCRATCH}/{component}/{receipt_name}"),
                f"{component} near-twin receipt {receipt_name} exists",
            )
    check(
        open(f"{SCRATCH}/near-twin-dump.exit").read().strip() == "0",
        "near-twin dump exit 0",
    )
    for component in COMPONENTS:
        left, right = NEAR_TWINS[component]
        print(
            f"   {component} near-twin paths {left} ({names[left][0]}) vs "
            f"{right} ({names[right][0]}):"
        )
        print(f"      census pair structure between the twins: {twin_census[component]}")
        _near_twin_report(component, left, right)

    print("\n== phase 7: the verdict table")
    verdict = {}
    for label, locus_map in (("TAIL", TAIL_LOCI), ("CONTROL", CONTROL_LOCI)):
        for component in COMPONENTS:
            for locus in locus_map[component]:
                receipt = receipts[component][locus]
                table = locus_tables[component].get(locus)
                mass = receipt["observed_node_mass"] + receipt["observed_edge_mass"]
                if not table:
                    continue
                row = {
                    "mass": mass,
                    "rank": receipt.get("truth_rank"),
                    "collected": table["collected_homing"],
                    "frame": table["frame_homing"],
                    "f": table["f_homing"],
                    "g": table["g_homing"],
                    "h": table["h_homing"],
                    "i": table["i_homing"] + table["i_nonhoming"],
                    "j": table["j_homing"] + table["j_nonhoming"],
                    "nonhoming_f": table["f_nonhoming"],
                    "nonhoming_g": table["g_nonhoming"],
                    "nonhoming_h": table["h_nonhoming"],
                    "dilution": table["homing_t_mass"] - table["homing_mass"],
                    "on_truth": dict(table["on_truth_sequence"]),
                    "off_truth": dict(table["off_truth_sequence"]),
                }
                verdict[(component, locus, label)] = row
                leak = row["f"] + row["g"] + row["h"] + row["i"] + row["j"]
                on_total = sum(row["on_truth"].values())
                off_total = sum(row["off_truth"].values())
                print(
                    f"   {label} {component} L{locus}: rank {row['rank']} mass {mass:.1f} | "
                    f"truth-leak {leak:.1f} ({100.0 * leak / mass if mass else 0:.1f}%): "
                    f"f {row['f']:.1f} | g {row['g']:.1f} | h {row['h']:.1f} | "
                    f"i {row['i']:.1f} | j {row['j']:.1f} | frame {row['frame']:.1f} | "
                    f"collected {row['collected']:.1f} | dilution {row['dilution']:.1f} | "
                    f"non-homing off-truth f/g/h {row['nonhoming_f']:.1f}/"
                    f"{row['nonhoming_g']:.1f}/{row['nonhoming_h']:.1f} | "
                    f"leak on-truth-sequence {on_total:.1f} / foreign {off_total:.1f}"
                )
    pooled = {label: collections.Counter() for label in ("TAIL", "CONTROL")}
    for (component, locus, label), row in verdict.items():
        for key in ("f", "g", "h", "i", "j", "frame", "collected", "dilution"):
            pooled[label][key] += row[key]
    for label in ("TAIL", "CONTROL"):
        row = pooled[label]
        leak = row["f"] + row["g"] + row["h"] + row["i"] + row["j"]
        print(
            f"   POOLED {label}: truth-leak {leak:.1f} share units | "
            f"f {row['f']:.1f} | g {row['g']:.1f} | h {row['h']:.1f} | "
            f"i {row['i']:.1f} | j {row['j']:.1f} | frame {row['frame']:.1f} | "
            f"collected {row['collected']:.1f} | dilution {row['dilution']:.1f}"
        )

    print("\n== summary")
    if FAILURES:
        print(f"FAILURES: {len(FAILURES)}")
        for message in FAILURES:
            print(f"  - {message}")
        return 1
    print("ALL PHASES PASS")
    return 0


def _merged_spans(spans):
    spans = sorted(spans)
    out = []
    for lo, hi in spans:
        if out and lo <= out[-1][1]:
            out[-1][1] = max(out[-1][1], hi)
        else:
            out.append([lo, hi])
    return out


def _near_twin_report(component, left, right):
    """The condensation answer for one named near-twin route pair, from
    the walk and homology receipts: shared vs parallel nodes, and where
    the distinguishing material sits."""
    base = f"{SCRATCH}/{component}"
    walks = {}
    for path in (left, right):
        steps = []
        with open(f"{base}/near-twin-walk-{path}.tsv") as handle:
            for line in handle:
                bp, node = line.split()
                steps.append((int(bp), int(node)))
        walks[path] = steps
    left_nodes = {abs(node) for _, node in walks[left]}
    right_nodes = {abs(node) for _, node in walks[right]}
    shared = left_nodes & right_nodes
    print(
        f"      walks: {len(walks[left]):,d} steps vs {len(walks[right]):,d} steps; "
        f"shared nodes {len(shared):,d} "
        f"({100.0 * len(shared) / len(left_nodes):.1f}% of left's {len(left_nodes):,d} nodes, "
        f"{100.0 * len(shared) / len(right_nodes):.1f}% of right's {len(right_nodes):,d})"
    )
    # The syng's own alignment provenance between the twins, full anchors:
    # the anchors ARE the shared syncmers the syng itself chains.
    anchor_count = 0
    anchored_nodes = set()
    covered_left = []
    covered_right = []
    with open(f"{base}/near-twin-homology-{left}-{right}.jsonl") as handle:
        for line in handle:
            row = json.loads(line)
            if row.get("request_done") or row["target_path"] != right:
                continue
            for query_pos, target_pos, node in row["anchors"]:
                anchor_count += 1
                anchored_nodes.add(node)
                covered_left.append((query_pos, query_pos + K))
                covered_right.append((target_pos, target_pos + K))
    left_covered = _merged_spans(covered_left)
    right_covered = _merged_spans(covered_right)
    left_bp = sum(hi - lo for lo, hi in left_covered)
    right_bp = sum(hi - lo for lo, hi in right_covered)
    left_len = walks[left][-1][0] + K if walks[left] else 1
    right_len = walks[right][-1][0] + K if walks[right] else 1
    print(
        f"      syng homology {left}->{right}: {anchor_count:,d} shared-syncmer anchors "
        f"({len(anchored_nodes):,d} distinct nodes), aligned coverage "
        f"{left_bp:,d} bp of left ({100.0 * left_bp / left_len:.1f}%), "
        f"{right_bp:,d} bp of right ({100.0 * right_bp / right_len:.1f}%)"
    )
    incidental = shared - anchored_nodes
    print(
        f"      shared-node structure: {len(anchored_nodes):,d} chained by the syng's "
        f"anchors, {len(incidental):,d} shared but outside the anchor chain"
    )
    # The distinguishing material: maximal runs of consecutive steps whose
    # nodes the other twin does not carry.
    for path, other_nodes, label in ((left, right_nodes, "left"), (right, left_nodes, "right")):
        runs = []
        run = None
        for bp, node in walks[path]:
            if abs(node) not in other_nodes:
                if run is None:
                    run = [bp, bp + K]
                else:
                    run[1] = bp + K
            else:
                if run is not None:
                    runs.append(tuple(run))
                    run = None
        if run is not None:
            runs.append(tuple(run))
        runs_by_size = sorted(runs, key=lambda span: span[1] - span[0], reverse=True)
        print(
            f"      {label}-only (parallel) material: {len(runs_by_size)} runs, "
            f"{sum(span[1] - span[0] for span in runs_by_size):,d} bp; "
            f"largest {['%d-%d' % span for span in runs_by_size[:5]]}"
        )


if __name__ == "__main__":
    sys.exit(main())
